### ISSUE TITLE
Possible DF beta bug

### ISSUE THREAD

**Issue by ZINK-ZINK** [funkydude/BugSack#75] opened 2022-10-08 23:55 UTC
Using the build from about October 3rd. This error is probably being misattributed, but it's not everyday I get to report a bug from Bugsack itself lol. It errored from opening the [Default WoW] Options menu.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'BugSack' tried to call the protected function 'SpellStopCasting()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SpellStopCasting'
[string "@Interface/FrameXML/UIParent.lua"]:4003: in function `ToggleGameMenu'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:203: in function `TransitionBackOpeningPanel'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:192: in function `ExitWithCommit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:168: in function `Close'
[string "@Interface/FrameXML/UIParent.lua"]:3981: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

**Comment by plusmouse** [comment] 2022-10-10 08:45
This is caused by dropdown taint. To replicate open the BugSack options and use a dropdown found there (don't need to change its value, just opening it is enough) and then open Edit Mode.

**Comment by raechu** [comment] 2022-10-14 01:39
Same reproduction method as above, but when I do it, it errors attempting to call a different protected function:

`2x [ADDON_ACTION_FORBIDDEN] AddOn 'BugSack' tried to call the protected function 'TargetUnit()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/FrameXML/EditModeManager.lua"]:1500: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1431: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:192: in function <Interface/FrameXML/EditModeManager.lua:190>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2846: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2650: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2554: in function <Interface/FrameXML/UIParent.lua:2550>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3152: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>`

**Comment by funkydude** [comment] 2023-01-28 00:11
Gonna go ahead and close this. I've not seen it but let me know if it still happens.

**Closed by funkydude** 2023-01-28 00:11 UTC
Labels: retail
