### ISSUE TITLE
Can't browse through all sounds

### ISSUE THREAD

**Issue by Anothersignup** [funkydude/BugSack#93] opened 2023-07-01 11:28 UTC
## Describe the problem
Can't browse through all sounds.
The upper part of the popup window will not show and scrolling does not work.

### What steps will reproduce the problem?

1.  
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
10.1.3.

**Comment by funkydude** [comment] 2023-07-11 15:58
Duplicate of #16

**Closed by funkydude** 2023-07-11 15:58 UTC
Labels: retail
