### ISSUE TITLE
[Lua Error] - bad argument #1 to 'gsub' (string expected, got nil)

### ISSUE THREAD

**Issue by boktai1000** [funkydude/BugSack#72] opened 2022-09-26 21:28 UTC
## Describe the problem
Lua Error - Pasted below under error log

### What steps will reproduce the problem?

N/A - Seemed to happen randomly, but what I was doing when it occurred posted below

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![image](https://user-images.githubusercontent.com/9054563/192383672-b7c73c00-a4a9-4e05-ae44-a096bf7e80a6.png)

### What version of the addon are you using? (Stating 'latest' is not useful)

**9.2.5**

### Do you have an error log of what happened?

```
14x ...BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0-5.lua:247: bad argument #1 to 'gsub' (string expected, got nil)
[string "=[C]"]: ?
[string "@BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0-5.lua"]:247: in function `Deserialize'
[string "@Details\core\network.lua"]:404: in function `func'
[string "@Details\core\network.lua"]:648: in function `?'
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Attune\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:218: in function `OnReceiveMultipartLast'
[string "@Attune\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:256: in function <...rfaceAttune\Libs\AceComm-3.0\AceComm-3.0.lua:246>
```

### Any additional information? (example: WoW language if not English)

Was farming Scholomance on my 70 Draenei Paladin, flew from Isle of Quel'Danas and went to Scholomance to reset the dungeon 5 times for a boss. This toon is a boosted toon as well, if that matters.

**Comment by boktai1000** [comment] 2022-09-26 21:29
[220926_BugSack_LUA1.txt](https://github.com/funkydude/BugSack/files/9649774/220926_BugSack_LUA1.txt)

**Comment by funkydude** [comment] 2022-09-27 01:07
Closing as duplicate of #66

(This was also opened by you and explained as an issue in Details)

**Closed by funkydude** 2022-09-27 01:07 UTC
Labels: wotlkc
